[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gloo-console = "0.2.3"
gloo-net = "0.2.6"
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.94"
static_routes.workspace = true
interfacing.workspace = true
stylist = { version = "0.12.0", features = ["yew"] }
wasm-bindgen-futures = "0.4.34"
web-sys = "0.3.61"
yew = { version = "0.20.0", features = ["csr"] }
yew-router = "0.17.0"
secrecy = { version = "0.8.0", features = ["serde"] }