[workspace]
members = ["backend", "frontend", "database", "common"]
default-members = ["backend"]

[workspace.dependencies]
static_routes = { path = "common/static_routes" }
interfacing = { path = "common/interfacing" }
secrecy = { version = "0.8.0", features = ["serde"] }
serde = { version = "1.0.159", features = ["derive"] }
serde_json = "1.0.94"
bonsaidb = { version = "0.4.1", features = ["server-full", "client-full", "local", "local-async"] }