[package]
name = "api_aga_in"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "api_aga_in"

[dependencies]
axum = "0.6.10"
hyper = "0.14.24"
tokio = { version = "1.26.0", features = ["full"] }

[features]

[dev-dependencies]
reqwest = "0.11.14"
