[package]
name = "api_aga_in"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "api_aga_in"

[dependencies]
axum = "0.6.10"
bonsaidb = { version = "0.4.1", features = ["local", "local-async"] }
config = "0.13.3"
hyper = "0.14.24"
once_cell = "1.17.1"
serde = { version = "1.0.152", features = ["derive"] }
serial_test = "1.0.0"
tokio = { version = "1.26.0", features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.4.0", features = ["trace"] }
tracing = { version = "0.1.37", features = ["log"] }
tracing-bunyan-formatter = "0.3.6"
tracing-log = "0.1.3"
tracing-subscriber = { version = "0.3.16", features = ["registry", "env-filter"] }
uuid = { version = "1.3.0", features = ["v4"] }

[features]

[dev-dependencies]
reqwest = "0.11.14"
