[package]
name = "database"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
bonsaidb = { version = "0.4.1", features = ["server"] }
serde.workspace = true
tokio = "1.28.0"
