application:
    port: 8000
    hmac_secret: "super-long-and-secret-random-key-needed-to-verify-message-integrity"

database:
    dir: "basic.bonsaidb"
    memory_only: false

email_client:
    base_url: "http://127.0.0.1"
    sender_email: "test@gmail.com"
    authorization_token: "preciously-secret"
    timeout_milliseconds: 10000

testing:
    database:
        dir: "target/tmp/test/basic.bonsaidb"
        memory_only: true

    application:
        port: 0
        host: 127.0.0.1
        base_url: "http://127.0.0.1"
        # FIXIT
        # not accessed/cannot be accessed
        # application.hmac_secret used instead
        hmac_secret: ""