application:
    port: 8000

database:
    dir: "basic.bonsaidb"

testing:
    database:
        dir: "target/tmp/test/basic.bonsaidb"

email_client:
    base_url: "localhost"
    sender_email: "test@gmail.com"