[package]
name = "db"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempdir = "0.3.7"
bonsaidb.workspace = true
serde.workspace = true
anyhow.workspace = true
domain = { path = "../domain" }