# APP_ENVIRONMENT=local
# REQUIRES:
#

application:
    host: 127.0.0.1
    base_url: "http://127.0.0.1"

email_client:
    authorization_token: "preciously-secret"

database:
    host: "localhost"
    password: "1"