# APP_ENVIRONMENT=production
# REQUIRES:
# APP__APPLICATION__BASE_URL
# APP__APPLICATION__SESSION_SECRET
# APP__EMAIL_CLIENT__AUTHORIZATION_TOKEN
# APP__DATABASE__HOST
# APP__DATABASE__PASSWORD

application:
    host: 0.0.0.0

email_client:
    base_url: "https://api.postmarkapp.com"
    sender_email: "phantie@phantie.com"

database:
    host: "localhost"