# APP_ENVIRONMENT=production
# REQUIRES:
# APP__APPLICATION__BASE_URL
# APP__EMAIL_CLIENT__AUTHORIZATION_TOKEN

application:
    host: 0.0.0.0

email_client:
    base_url: "https://api.postmarkapp.com"
    sender_email: "phantie@phantie.com"
