name: testing # huh

on:
  pull_request:

  push:
    branches: [master]

jobs:
  db-cli:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - run: 
        echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

    - uses: mozilla-actions/sccache-action@v0.0.3

    - name: Run tests
      working-directory: ./database/cli
      run: cargo test --verbose

env:
  CARGO_TERM_COLOR: always
