name: testing

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  common_static_routes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./common/static_routes
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./common/static_routes
      run: cargo test --verbose

  common_auth:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./common/auth
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./common/auth
      run: cargo test --verbose

env:
  CARGO_TERM_COLOR: always
