name: testing

on:
  pull_request:

  push:
    branches: [master]

jobs:
  db-cli:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure sccache env var and set build profile to ephemeral build
      run: | 
        echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
        echo “SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.2

    - name: Build
      working-directory: ./database/cli
      run: cargo build --verbose
  
    - name: Run tests
      working-directory: ./database/cli
      run: cargo test --verbose

env:
  CARGO_TERM_COLOR: always
